### ISSUE TITLE
Composer install fails Symfony 2.3

### ISSUE THREAD

**Issue by manzwebdesigns** [victorhaggqvist/Twig-sort-by-field#3]
When I do the composer install, I get the following:

>composer require snilius/twig-sort-by-field
>Using version ^0.1.3 for snilius/twig-sort-by-field
>./composer.json has been updated
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - The requested package doctrine/orm == 2.4.8.0 could not be found.
>  Problem 2
>    - Conclusion: don't install doctrine/orm v2.3.6
>    - Conclusion: don't install doctrine/orm 2.3.5
>    - Conclusion: don't install doctrine/orm 2.3.4
>    - Conclusion: don't install doctrine/orm 2.3.3
>    - Conclusion: don't install doctrine/orm 2.3.2
>    - Conclusion: don't install doctrine/orm 2.3.1
>    - Conclusion: don't install doctrine/orm 2.3.0
>    - Conclusion: don't install doctrine/common 2.2.0
>    - Conclusion: don't install doctrine/cache v1.4.2|install doctrine/common 2.2.0
>    - Installation request for doctrine/common == 2.5.1.0 -> satisfiable by doctrine/common[v2.5.1].
>    - Installation request for doctrine/orm >=2.2.3,<2.4 -> satisfiable by doctrine/orm[2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, v2.3.6].
>    - Conclusion: remove doctrine/cache v1.4.2|install doctrine/common 2.2.0
>    - doctrine/orm 2.2.3 requires doctrine/common 2.2.* -> satisfiable by doctrine/common[2.2.0, 2.2.1, 2.2.2, 2.2.3].
>    - doctrine/common 2.2.1 conflicts with doctrine/cache[v1.4.2].
>    - doctrine/common 2.2.2 conflicts with doctrine/cache[v1.4.2].
>    - doctrine/common 2.2.3 conflicts with doctrine/cache[v1.4.2].
>    - Installation request for doctrine/cache == 1.4.2.0 -> satisfiable by doctrine/cache[v1.4.2].
>
>Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
>
>Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
>
>Installation failed, reverting ./composer.json to its original content.

Here is my composer.json:

```javascript
cat composer.json 
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": ">=2.2.3,<2.4",
        "doctrine/doctrine-bundle": "1.2.*",
        "doctrine/doctrine-migrations-bundle": "dev-master",
        "doctrine/migrations": "dev-master",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "jms/security-extra-bundle": "dev-master",
        "jms/di-extra-bundle": "dev-master",
        "kriswallsmith/assetic": "1.1.*@dev",
        "friendsofsymfony/user-bundle": "*",
        "jms/serializer-bundle": "0.11",
        "friendsofsymfony/jsrouting-bundle": "2.0.*@dev",
        "egeloen/ckeditor-bundle": "2.*",
        "knplabs/gaufrette": "dev-master",
        "knplabs/knp-gaufrette-bundle" : "dev-master",
        "vich/uploader-bundle": "0.9.*",
        "knplabs/knp-paginator-bundle": "~2.3"
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web"
    },
     "minimum-stability": "dev" 
}
```

**Comment by victorhaggqvist** [comment]
This seem unrelated.

The composer output complains about `doctrine/orm`, which have nothing to do with this.

    The requested package doctrine/orm == 2.4.8.0 could not be found.

Also I just tested to run a `composer require snilius/twig-sort-by-field` with your `composer.json` with no problem. Try again it will likely work, other ways it probably something else wrong.

**Comment by manzwebdesigns** [comment]
Hi Victor,

Thanks for the speedy reply!  I figured it out... I wasn't allowing composer install a high enough version of some of the entries.  All is good now!

Thanks,
Bud
