### ISSUE TITLE
The filter "sortbyfield" does not exist on symfony 2.7

### ISSUE THREAD

**Issue by elgui02** [victorhaggqvist/Twig-sort-by-field#4]
Hi i have this error " The filter "sortbyfield" does not exist " i install with composer but, maybe i forget any steps??

code: {%for pregunta in item.itempregunta | sortbyfield('Orden') %}

**Comment by victorhaggqvist** [comment]
Just installing via Composer is not good enough. You need to make Twig aware of it also by adding it.
```php
$twig->addExtension(new SortByFieldExtension());
```

See the test for more context. https://github.com/victorhaggqvist/Twig-sort-by-field/blob/master/test/SortByFieldExtensionTest.php#L17
