### ISSUE TITLE
No sort objects

### ISSUE THREAD

**Issue by savritsky** [victorhaggqvist/Twig-sort-by-field#7]
The code is checked:
if (!is_array($content)) {
    throw new \InvalidArgumentException('Variable passed to the sortByField filter is not an array');
}
and no sort objects

**Comment by victorhaggqvist** [comment]
I'm not quite sure what you are trying to tell me. The filter do support sorting of objects https://github.com/victorhaggqvist/Twig-sort-by-field/blob/master/test/SortByFieldExtensionTest.php#L106.
